# Generated by Django 5.2.3 on 2025-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_feedback_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Отправка на почту')),
                ('telegram_enabled', models.BooleanField(default=True, verbose_name='Отправка в телеграм')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='Отправка в вацап')),
                ('db_save_enabled', models.BooleanField(default=True, verbose_name='Сохранение в БД')),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email отправителя')),
                ('email_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль отправителя')),
                ('email_host', models.CharField(default='smtp.yandex.ru', max_length=255, verbose_name='SMTP сервер')),
                ('email_port', models.IntegerField(default=465, verbose_name='SMTP порт')),
                ('email_use_ssl', models.BooleanField(default=True, verbose_name='Использовать SSL')),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма')),
                ('email_recipients', models.TextField(default='studenikin000@yandex.ru', help_text='Пример: email1@example.com, email2@example.com', verbose_name='Получатели (через запятую)')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен бота')),
                ('telegram_chat_ids', models.TextField(blank=True, help_text='Пример: 123456789, 987654321', null=True, verbose_name='ID чатов (через запятую)')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
